/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Mannager.ComboBox;
import Mannager.Delete;
import Mannager.Save;

/**
 *
 * @author Chazool
 */
public class GUICreateBatchandClassPlace extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUICreateBatchandClassPlace() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        leyerBackground = new javax.swing.JLayeredPane();
        leyerDisigng = new javax.swing.JLayeredPane();
        jLayeredPane14 = new javax.swing.JLayeredPane();
        jLayeredPane15 = new javax.swing.JLayeredPane();
        jLayeredPane16 = new javax.swing.JLayeredPane();
        jLabel27 = new javax.swing.JLabel();
        txtClassPlace = new javax.swing.JTextField();
        butAddClassPlace = new javax.swing.JButton();
        jLayeredPane17 = new javax.swing.JLayeredPane();
        jLabel28 = new javax.swing.JLabel();
        butDleteClassPlace = new javax.swing.JButton();
        ComboDelClassPlace = new javax.swing.JComboBox();
        jLayeredPane18 = new javax.swing.JLayeredPane();
        jLayeredPane19 = new javax.swing.JLayeredPane();
        jLabel32 = new javax.swing.JLabel();
        ButDeleteBatch = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        ComboBatchDeleteClassPlace = new javax.swing.JComboBox();
        ComboDelBatchyear = new javax.swing.JComboBox();
        jLayeredPane20 = new javax.swing.JLayeredPane();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        CalBatchyear = new com.toedter.calendar.JYearChooser();
        CalBatchStartDate = new com.toedter.calendar.JDateChooser();
        ButBatchClear = new javax.swing.JToggleButton();
        jLabel35 = new javax.swing.JLabel();
        ComboBatchlClassPlace = new javax.swing.JComboBox();
        ButCreteBatch = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ComboOption1 = new javax.swing.JComboBox();
        ComboOption2 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Managment");

        jLayeredPane15.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Place"));

        jLayeredPane16.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Class Place"));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Class Place :");

        txtClassPlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtClassPlace.setEnabled(false);

        butAddClassPlace.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butAddClassPlace.setText("Add");
        butAddClassPlace.setEnabled(false);
        butAddClassPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddClassPlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane16Layout = new javax.swing.GroupLayout(jLayeredPane16);
        jLayeredPane16.setLayout(jLayeredPane16Layout);
        jLayeredPane16Layout.setHorizontalGroup(
            jLayeredPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAddClassPlace)
                    .addComponent(txtClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane16Layout.setVerticalGroup(
            jLayeredPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane16Layout.createSequentialGroup()
                .addGroup(jLayeredPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butAddClassPlace)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane16.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane16.setLayer(txtClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane16.setLayer(butAddClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane17.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Class Place"));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Class Place :");

        butDleteClassPlace.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butDleteClassPlace.setText("Delete");
        butDleteClassPlace.setEnabled(false);
        butDleteClassPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDleteClassPlaceActionPerformed(evt);
            }
        });

        ComboDelClassPlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ComboDelClassPlace.setEnabled(false);

        javax.swing.GroupLayout jLayeredPane17Layout = new javax.swing.GroupLayout(jLayeredPane17);
        jLayeredPane17.setLayout(jLayeredPane17Layout);
        jLayeredPane17Layout.setHorizontalGroup(
            jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane17Layout.createSequentialGroup()
                        .addComponent(butDleteClassPlace)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboDelClassPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane17Layout.setVerticalGroup(
            jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane17Layout.createSequentialGroup()
                .addGroup(jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(ComboDelClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butDleteClassPlace)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane17.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane17.setLayer(butDleteClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane17.setLayer(ComboDelClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane15Layout = new javax.swing.GroupLayout(jLayeredPane15);
        jLayeredPane15.setLayout(jLayeredPane15Layout);
        jLayeredPane15Layout.setHorizontalGroup(
            jLayeredPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jLayeredPane17))
                .addContainerGap())
        );
        jLayeredPane15Layout.setVerticalGroup(
            jLayeredPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane15.setLayer(jLayeredPane16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane15.setLayer(jLayeredPane17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane18.setBorder(javax.swing.BorderFactory.createTitledBorder("Batch"));

        jLayeredPane19.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Batch"));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Clas Place :");

        ButDeleteBatch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ButDeleteBatch.setText("Delete");
        ButDeleteBatch.setEnabled(false);
        ButDeleteBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteBatchActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Batch Year :");

        ComboBatchDeleteClassPlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ComboBatchDeleteClassPlace.setEnabled(false);
        ComboBatchDeleteClassPlace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBatchDeleteClassPlaceItemStateChanged(evt);
            }
        });

        ComboDelBatchyear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ComboDelBatchyear.setEnabled(false);

        javax.swing.GroupLayout jLayeredPane19Layout = new javax.swing.GroupLayout(jLayeredPane19);
        jLayeredPane19.setLayout(jLayeredPane19Layout);
        jLayeredPane19Layout.setHorizontalGroup(
            jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane19Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane19Layout.createSequentialGroup()
                        .addComponent(ButDeleteBatch)
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addComponent(ComboDelBatchyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBatchDeleteClassPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane19Layout.setVerticalGroup(
            jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(ComboBatchDeleteClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(ComboDelBatchyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButDeleteBatch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane19.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane19.setLayer(ButDeleteBatch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane19.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane19.setLayer(ComboBatchDeleteClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane19.setLayer(ComboDelBatchyear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane20.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Batch"));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Start Date :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Class Plase :");

        CalBatchyear.setEnabled(false);

        CalBatchStartDate.setEnabled(false);
        CalBatchStartDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ButBatchClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ButBatchClear.setText("Clear");
        ButBatchClear.setEnabled(false);
        ButBatchClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBatchClearActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Batch Year :");

        ComboBatchlClassPlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ComboBatchlClassPlace.setEnabled(false);

        ButCreteBatch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ButCreteBatch.setText("Crate");
        ButCreteBatch.setEnabled(false);
        ButCreteBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCreteBatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane20Layout = new javax.swing.GroupLayout(jLayeredPane20);
        jLayeredPane20.setLayout(jLayeredPane20Layout);
        jLayeredPane20Layout.setHorizontalGroup(
            jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane20Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel35)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane20Layout.createSequentialGroup()
                        .addComponent(ButCreteBatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButBatchClear))
                    .addComponent(ComboBatchlClassPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane20Layout.createSequentialGroup()
                        .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalBatchyear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CalBatchStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane20Layout.setVerticalGroup(
            jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(CalBatchyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBatchlClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalBatchStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCreteBatch)
                    .addComponent(ButBatchClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane20.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(CalBatchyear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(CalBatchStartDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(ButBatchClear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(ComboBatchlClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane20.setLayer(ButCreteBatch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane18Layout = new javax.swing.GroupLayout(jLayeredPane18);
        jLayeredPane18.setLayout(jLayeredPane18Layout);
        jLayeredPane18Layout.setHorizontalGroup(
            jLayeredPane18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane18Layout.createSequentialGroup()
                .addComponent(jLayeredPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane18Layout.setVerticalGroup(
            jLayeredPane18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane19))
        );
        jLayeredPane18.setLayer(jLayeredPane19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane18.setLayer(jLayeredPane20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ComboOption1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ComboOption1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Class Place", "Batch" }));
        ComboOption1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboOption1ItemStateChanged(evt);
            }
        });

        ComboOption2.setEditable(true);
        ComboOption2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ComboOption2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Add", "Delete" }));
        ComboOption2.setEnabled(false);
        ComboOption2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboOption2ItemStateChanged(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Option 1 :");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Option 2 :");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(ComboOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(ComboOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(ComboOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(ComboOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(ComboOption1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ComboOption2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane14Layout = new javax.swing.GroupLayout(jLayeredPane14);
        jLayeredPane14.setLayout(jLayeredPane14Layout);
        jLayeredPane14Layout.setHorizontalGroup(
            jLayeredPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane14Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLayeredPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        jLayeredPane14Layout.setVerticalGroup(
            jLayeredPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jLayeredPane14.setLayer(jLayeredPane15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane14.setLayer(jLayeredPane18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane14.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout leyerDisigngLayout = new javax.swing.GroupLayout(leyerDisigng);
        leyerDisigng.setLayout(leyerDisigngLayout);
        leyerDisigngLayout.setHorizontalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane14)
        );
        leyerDisigngLayout.setVerticalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane14)
        );
        leyerDisigng.setLayer(jLayeredPane14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leyerBackground.add(leyerDisigng);
        leyerDisigng.setBounds(0, 0, 1100, 640);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        leyerBackground.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 630);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1120, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Disable() {
        String option1 = ComboOption1.getSelectedItem().toString();
        String option2 = ComboOption2.getSelectedItem().toString();
        boolean bool = false, boolCassAdd = false, BoolClassDel = false, BoolBatchAdd = false, BoolBatchDel = false;

        switch (option1) {
            case "Class Place":
                bool = true;
                switch (option2) {
                    case "Add":
                        boolCassAdd = true;
                        BoolClassDel = false;

                        break;
                    case "Delete":
                        ComboDelClassPlace.setModel(ComboBox.SetClassPlace());
                        boolCassAdd = false;
                        BoolClassDel = true;

                        break;
                }
                break;
            case "Batch":
                bool = true;
                switch (option2) {
                    case "Add":
                        ComboBatchlClassPlace.setModel(ComboBox.SetClassPlace());
                        BoolBatchAdd = true;
                        BoolBatchDel = false;

                        break;
                    case "Delete":
                        ComboBatchDeleteClassPlace.setModel(ComboBox.SetClassPlace());
                        ComboDelBatchyear.setModel(ComboBox.SetBatchyear(ComboBatchDeleteClassPlace.getSelectedItem().toString().trim()));
                        BoolBatchAdd = false;
                        BoolBatchDel = true;

                        break;
                }
                break;
        }

        // Class Place
        txtClassPlace.setEnabled(boolCassAdd);
        butAddClassPlace.setEnabled(boolCassAdd);
        ComboDelClassPlace.setEnabled(BoolClassDel);
        butDleteClassPlace.setEnabled(BoolClassDel);

        // Batch
        CalBatchyear.setEnabled(BoolBatchAdd);
        CalBatchStartDate.setEnabled(BoolBatchAdd);
        ComboBatchlClassPlace.setEnabled(BoolBatchAdd);
        ButBatchClear.setEnabled(BoolBatchAdd);
        ButCreteBatch.setEnabled(BoolBatchAdd);
        ComboDelBatchyear.setEnabled(BoolBatchDel);
        ComboBatchDeleteClassPlace.setEnabled(BoolBatchDel);
        ButDeleteBatch.setEnabled(BoolBatchDel);

        ComboOption2.setEnabled(bool);
    }


    private void butAddClassPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddClassPlaceActionPerformed

        txtClassPlace.setText(Save.ClassPlace(txtClassPlace.getText()));

    }//GEN-LAST:event_butAddClassPlaceActionPerformed

    private void ButDeleteBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteBatchActionPerformed

        ComboDelBatchyear.setModel(Delete.Batch(ComboDelBatchyear.getSelectedItem().toString().trim(), ComboBatchDeleteClassPlace.getSelectedItem().toString()));

    }//GEN-LAST:event_ButDeleteBatchActionPerformed

    private void ButBatchClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBatchClearActionPerformed
        
    }//GEN-LAST:event_ButBatchClearActionPerformed

    private void ComboOption1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboOption1ItemStateChanged
        Disable();
    }//GEN-LAST:event_ComboOption1ItemStateChanged

    private void ComboOption2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboOption2ItemStateChanged
        Disable();
    }//GEN-LAST:event_ComboOption2ItemStateChanged

    private void butDleteClassPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDleteClassPlaceActionPerformed

        ComboDelClassPlace.setModel(Delete.ClassPlace(ComboDelClassPlace.getSelectedItem().toString().trim()));
    }//GEN-LAST:event_butDleteClassPlaceActionPerformed

    private void ButCreteBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCreteBatchActionPerformed

        Save.Batch(CalBatchyear.getYear(),CalBatchStartDate.getDate(), ComboBatchlClassPlace.getSelectedItem().toString());


    }//GEN-LAST:event_ButCreteBatchActionPerformed

    private void ComboBatchDeleteClassPlaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBatchDeleteClassPlaceItemStateChanged
        ComboDelBatchyear.setModel(ComboBox.SetBatchyear(ComboBatchDeleteClassPlace.getSelectedItem().toString().trim()));

    }//GEN-LAST:event_ComboBatchDeleteClassPlaceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICreateBatchandClassPlace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICreateBatchandClassPlace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICreateBatchandClassPlace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICreateBatchandClassPlace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICreateBatchandClassPlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButBatchClear;
    private javax.swing.JToggleButton ButCreteBatch;
    private javax.swing.JButton ButDeleteBatch;
    private com.toedter.calendar.JDateChooser CalBatchStartDate;
    private com.toedter.calendar.JYearChooser CalBatchyear;
    private javax.swing.JComboBox ComboBatchDeleteClassPlace;
    private javax.swing.JComboBox ComboBatchlClassPlace;
    private javax.swing.JComboBox ComboDelBatchyear;
    private javax.swing.JComboBox ComboDelClassPlace;
    private javax.swing.JComboBox ComboOption1;
    private javax.swing.JComboBox ComboOption2;
    private javax.swing.JButton butAddClassPlace;
    private javax.swing.JButton butDleteClassPlace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane14;
    private javax.swing.JLayeredPane jLayeredPane15;
    private javax.swing.JLayeredPane jLayeredPane16;
    private javax.swing.JLayeredPane jLayeredPane17;
    private javax.swing.JLayeredPane jLayeredPane18;
    private javax.swing.JLayeredPane jLayeredPane19;
    private javax.swing.JLayeredPane jLayeredPane20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLayeredPane leyerBackground;
    private javax.swing.JLayeredPane leyerDisigng;
    private javax.swing.JTextField txtClassPlace;
    // End of variables declaration//GEN-END:variables
}
