/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bean.Student;
import DAO.SelectStudentData;
import Mannager.Check;
import java.awt.Color;

/**
 *
 * @author PCPAL
 */
public class GUIDeleteIndexSearch extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIDeleteIndexSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        leyerBackground = new javax.swing.JLayeredPane();
        leyerDisigng = new javax.swing.JLayeredPane();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        txtindex = new java.awt.TextField();
        ButDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay1 = new javax.swing.JTextArea();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplay2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Managment");

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtindex.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        txtindex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtindexKeyPressed(evt);
            }
        });

        ButDelete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ButDelete.setForeground(new java.awt.Color(0, 153, 102));
        ButDelete.setText("Delete");
        ButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 102));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtindex, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(ButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(ButDelete)
                .addGap(21, 21, 21))
        );
        jLayeredPane5.setLayer(txtindex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(ButDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtDisplay1.setColumns(20);
        txtDisplay1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtDisplay1.setForeground(new java.awt.Color(204, 51, 0));
        txtDisplay1.setRows(12);
        jScrollPane1.setViewportView(txtDisplay1);

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane9Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane9.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtDisplay2.setColumns(20);
        txtDisplay2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtDisplay2.setForeground(new java.awt.Color(204, 51, 0));
        txtDisplay2.setRows(12);
        jScrollPane2.setViewportView(txtDisplay2);

        javax.swing.GroupLayout jLayeredPane10Layout = new javax.swing.GroupLayout(jLayeredPane10);
        jLayeredPane10.setLayout(jLayeredPane10Layout);
        jLayeredPane10Layout.setHorizontalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        jLayeredPane10Layout.setVerticalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        jLayeredPane10.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout leyerDisigngLayout = new javax.swing.GroupLayout(leyerDisigng);
        leyerDisigng.setLayout(leyerDisigngLayout);
        leyerDisigngLayout.setHorizontalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leyerDisigngLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane9)
                    .addComponent(jLayeredPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane10)
                .addContainerGap())
        );
        leyerDisigngLayout.setVerticalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerDisigngLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leyerDisigngLayout.createSequentialGroup()
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        leyerDisigng.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerDisigng.setLayer(jLayeredPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerDisigng.setLayer(jLayeredPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leyerBackground.add(leyerDisigng);
        leyerDisigng.setBounds(0, 0, 1100, 640);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        leyerBackground.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 630);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1120, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SelectStudentData() {
        SelectStudentData StudentData = new SelectStudentData();
        if (Check.AttendantsValidation(txtindex.getText())) {
            Student std = StudentData.selectdata(txtindex.getText().trim());
            
            String index = "Index : " + std.getIndex();
            String BadgeYear = "Badgeyear : " + std.getIndex();
            String Classplasse = "ClassPlace : " + std.getIndex();
            String fullname = "Full Name : " + std.getFname() + " " + std.getMname() + " " + std.getSname();
            String nic = "NIC : " + std.getNic();
            String dob = "DOB : " + std.getDob();
            String gender = "Gender : " + std.getGender();
            String address = "Address : " + std.getAddress();
            String phone = "Phone : " + std.getPhonehome() + " / " + std.getPhonemobile();
            String email = "Email : " + std.getEmail();
            String imagepath;

            // Subject Data ...............................................
            // OL Data
            String OL1stYear = "O/L 1st Year : " + std.getOL1stYear() + " .... Index : " + std.getOLIndex1();
            String OL2ndYear = "O/L 2nd Year : " + std.getOL2ndYear() + " .... Index : " + std.getOLIndex2();
            
            String Science = "Science : " + std.getScience();
            String English = "English : " + std.getEnglish();
            String History = "History : " + std.getHistory();
            String Religion = "Religion : " + std.getReligion();
            String Sinhala = "Sinhala : " + std.getSinhala();
            String Maths = "Maths : " + std.getMaths();
            
            String subject1 = std.getSubject1() + " : " + std.getSubject1result();
            String subject2 = std.getSubject2() + " : " + std.getSubject2result();
            String subject3 = std.getSubject3() + " : " + std.getSubject3result();

            // Prent Data ...............................................
            String Pname = "Parent Name : " + std.getPfname() + " " + std.getPlname();
            String pnic = "Parent Nic : " + std.getPnic();
            String pphone = "Parent Phone : " + std.getPphone();
            String prelationship = "Parent Relationship : " + std.getPrelationship();
            
            String StdData = "Student Data........................... \n \n";
            String subdata = "Subject Data........................... \n \n";
            String PrentData = "Perent Data........................... \n \n";
            txtDisplay1.setText("");
            txtDisplay2.setText("");
            
            txtDisplay1.setForeground(Color.black);
            txtDisplay2.setForeground(Color.black);
            
            txtDisplay1.setText(StdData + index + "\n" + BadgeYear + "\n" + Classplasse + "\n" + fullname + "\n" + nic + "\n" + dob + "\n" + gender + "\n" + phone + "\n" + email);
            
            txtDisplay2.setText(subdata + OL1stYear + "\n" + OL2ndYear + "\n" + English + "\n" + History + "\n" + Religion + "\n" + Sinhala + "\n" + Maths + "\n" + subject1 + "\n" + subject2 + "\n" + subject3
            );
            
            txtDisplay2.setText(txtDisplay2.getText() + "\n \n" + PrentData + Pname + "\n" + pnic + "\n" + pphone + "\n" + prelationship);
            
        } else {
            String errormsg = "Invalid Index";
            txtDisplay1.setForeground(Color.red);
            txtDisplay2.setForeground(Color.red);
            txtDisplay1.setText(errormsg);
            txtDisplay2.setText(errormsg);
        }
        
    }

    private void txtindexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtindexKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            SelectStudentData();
        }
    }//GEN-LAST:event_txtindexKeyPressed

    private void ButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteActionPerformed

    }//GEN-LAST:event_ButDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        SelectStudentData();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDeleteIndexSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDeleteIndexSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDeleteIndexSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDeleteIndexSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDeleteIndexSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLayeredPane leyerBackground;
    private javax.swing.JLayeredPane leyerDisigng;
    private javax.swing.JTextArea txtDisplay1;
    private javax.swing.JTextArea txtDisplay2;
    private java.awt.TextField txtindex;
    // End of variables declaration//GEN-END:variables
}
