/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bean.TimeTable;
import DAO.DeleteTimeTable;
import DAO.SelectTimeTable;
import DAO.UpdateTimeTable;
import Mannager.ComboBox;
import Mannager.Delete;
import Mannager.Table;
import Mannager.Update;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Chazool
 */
public class GUIEditTimeTable extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIEditTimeTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        leyerBackground = new javax.swing.JLayeredPane();
        leyerDisigng = new javax.swing.JLayeredPane();
        leyerupdate = new javax.swing.JLayeredPane();
        comboDate = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboclasstype = new javax.swing.JComboBox();
        butupdate = new javax.swing.JToggleButton();
        comboclassplace = new javax.swing.JComboBox();
        SpinnerEndTimeH = new javax.swing.JSpinner();
        SpinnerStartTimeH = new javax.swing.JSpinner();
        SpinnerStartTimeM = new javax.swing.JSpinner();
        SpinnerEndTimeM = new javax.swing.JSpinner();
        ComboBatch = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTimeTable = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        comboSelectDate = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        butDelete = new javax.swing.JButton();
        radioUpdate = new javax.swing.JRadioButton();
        radioDelete = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Managment");

        leyerupdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        comboDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        comboDate.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("To");

        comboclasstype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboclasstype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Revision", "Theory", "Pepper" }));
        comboclasstype.setEnabled(false);

        butupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butupdate.setText("Update ");
        butupdate.setEnabled(false);
        butupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butupdateActionPerformed(evt);
            }
        });

        comboclassplace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboclassplace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Tangalle", "Matara", "Galle", "Colombo" }));
        comboclassplace.setEnabled(false);
        comboclassplace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboclassplaceItemStateChanged(evt);
            }
        });
        comboclassplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboclassplaceActionPerformed(evt);
            }
        });

        SpinnerEndTimeH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpinnerEndTimeH.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00"}));
        SpinnerEndTimeH.setEnabled(false);

        SpinnerStartTimeH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpinnerStartTimeH.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00"}));
        SpinnerStartTimeH.setEnabled(false);

        SpinnerStartTimeM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpinnerStartTimeM.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));
        SpinnerStartTimeM.setEnabled(false);

        SpinnerEndTimeM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpinnerEndTimeM.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));
        SpinnerEndTimeM.setEnabled(false);

        ComboBatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBatch.setEnabled(false);

        javax.swing.GroupLayout leyerupdateLayout = new javax.swing.GroupLayout(leyerupdate);
        leyerupdate.setLayout(leyerupdateLayout);
        leyerupdateLayout.setHorizontalGroup(
            leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerupdateLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(butupdate)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(leyerupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBatch, 0, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboclasstype, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leyerupdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(leyerupdateLayout.createSequentialGroup()
                            .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SpinnerStartTimeH)
                                .addComponent(SpinnerEndTimeH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SpinnerStartTimeM)
                                .addComponent(SpinnerEndTimeM, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)))
                    .addComponent(comboclassplace, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        leyerupdateLayout.setVerticalGroup(
            leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leyerupdateLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerEndTimeH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerEndTimeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leyerupdateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerStartTimeH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerStartTimeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboclassplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leyerupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboclasstype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butupdate)
                .addContainerGap())
        );
        leyerupdate.setLayer(comboDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(comboclasstype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(butupdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(comboclassplace, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(SpinnerEndTimeH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(SpinnerStartTimeH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(SpinnerStartTimeM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(SpinnerEndTimeM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerupdate.setLayer(ComboBatch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TblTimeTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TblTimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblTimeTable.setRowHeight(20);
        TblTimeTable.setRowMargin(2);
        TblTimeTable.setSurrendersFocusOnKeystroke(true);
        TblTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblTimeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblTimeTable);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        comboSelectDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboSelectDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        comboSelectDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSelectDateItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Select Date :");

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboSelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane6.setLayer(comboSelectDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        butDelete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butDelete.setText("Delete");
        butDelete.setEnabled(false);
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butDelete)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jLayeredPane7.setLayer(butDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(radioUpdate);
        radioUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioUpdate.setText(" Update  ");
        radioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUpdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDelete);
        radioDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioDelete.setText(" Delete  ");
        radioDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(radioUpdate)
                            .addGap(93, 93, 93)
                            .addComponent(radioDelete)
                            .addGap(41, 41, 41))))
                .addGap(20, 20, 20))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioUpdate)
                    .addComponent(radioDelete))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLayeredPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(radioUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(radioDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout leyerDisigngLayout = new javax.swing.GroupLayout(leyerDisigng);
        leyerDisigng.setLayout(leyerDisigngLayout);
        leyerDisigngLayout.setHorizontalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerDisigngLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(leyerDisigngLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(leyerupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leyerDisigngLayout.setVerticalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerDisigngLayout.createSequentialGroup()
                .addGroup(leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leyerDisigngLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(leyerupdate)
                        .addGap(18, 18, 18))
                    .addGroup(leyerDisigngLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        leyerDisigng.setLayer(leyerupdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerDisigng.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerDisigng.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leyerBackground.add(leyerDisigng);
        leyerDisigng.setBounds(0, 0, 1100, 640);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        leyerBackground.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 630);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1120, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static String primaryDate;
    public static String primaryStartTime;
    public static String primaryEndTime;

    private void SetUpdateForm() {

        setenableupdateform(true);

        int row = TblTimeTable.getSelectedRow();

        String date = TblTimeTable.getModel().getValueAt(row, 0).toString();
        String StartTime = TblTimeTable.getModel().getValueAt(row, 1).toString().trim();
        String EndTime = TblTimeTable.getModel().getValueAt(row, 2).toString().trim();

        // Set Primary Key
        primaryDate = date;
        primaryStartTime = StartTime;
        primaryEndTime = EndTime;
        //....................

        comboDate.setSelectedItem(date);
        SpinnerStartTimeH.setValue(TblTimeTable.getModel().getValueAt(row, 1).toString().substring(0, 2));
        SpinnerStartTimeM.setValue(TblTimeTable.getModel().getValueAt(row, 1).toString().substring(3, 5));
        SpinnerEndTimeH.setValue(TblTimeTable.getModel().getValueAt(row, 2).toString().substring(0, 2));
        SpinnerEndTimeM.setValue(TblTimeTable.getModel().getValueAt(row, 2).toString().substring(3, 5));
        comboclassplace.setSelectedItem(TblTimeTable.getModel().getValueAt(row, 3).toString().trim());
        comboclasstype.setSelectedItem(TblTimeTable.getModel().getValueAt(row, 4).toString());

    }

    private boolean Check() {

        Boolean bool = true;

        if (comboDate.getSelectedItem().equals(" ")) {
            comboDate.setBackground(Color.red);
            bool = false;
        } else {
            comboDate.setBackground(getBackground());
        }

        if (comboclassplace.getSelectedItem().equals(" ")) {
            comboclassplace.setBackground(Color.red);
            bool = false;
        } else {
            comboclassplace.setBackground(getBackground());

        }

        if (comboclasstype.getSelectedItem().equals(" ")) {
            comboclasstype.setBackground(Color.red);
            bool = false;
        } else {
            comboclasstype.setBackground(getBackground());
        }

        float x = Integer.parseInt(SpinnerStartTimeH.getValue() + "");
        float y = Integer.parseInt(SpinnerEndTimeH.getValue() + "");

        if (x < y) {
            SpinnerEndTimeH.setBackground(getBackground());
            SpinnerEndTimeM.setBackground(getBackground());
            SpinnerStartTimeH.setBackground(getBackground());
            SpinnerStartTimeM.setBackground(getBackground());
            butupdate.setBackground(getBackground());
        } else {
            SpinnerEndTimeH.setBackground(Color.red);

            SpinnerEndTimeM.setBackground(Color.red);
            SpinnerStartTimeH.setBackground(Color.red);
            SpinnerStartTimeM.setBackground(Color.red);
            butupdate.setBackground(Color.red);
            bool = false;

        }

        return bool;
    }

    private void DeleteOrUpdate() {
        if (radioUpdate.isSelected()) {
            butDelete.setEnabled(false);
            SetUpdateForm();
        } else {
            setenableupdateform(false);
            butDelete.setEnabled(true);
        }
    }

    private void update() {

        if (Check()) {
            Update.TimeTable(comboDate.getSelectedItem().toString().trim(),
                    SpinnerStartTimeH.getValue() + ":" + SpinnerStartTimeM.getValue(),
                    SpinnerEndTimeH.getValue() + ":" + SpinnerEndTimeM.getValue(),
                    comboclassplace.getSelectedItem().toString().trim(),
                    ComboBatch.getSelectedItem().toString().trim(),
                    comboclasstype.getSelectedItem().toString().trim());
        }
    }

    private void Delete() {
        TimeTable time = new TimeTable();
        TableModel Model = TblTimeTable.getModel();
        int raw = TblTimeTable.getSelectedRow();
        time.setDate(Model.getValueAt(raw, 0).toString());
        time.setStartTime(Model.getValueAt(raw, 1).toString());
        time.setEndTime(Model.getValueAt(raw, 2).toString());

        TblTimeTable.setModel(Delete.TimeTable(time, (DefaultTableModel) TblTimeTable.getModel(), comboSelectDate.getSelectedItem().toString().trim()));

    }

    public void clear() {
        comboDate.setSelectedItem("");
        comboclassplace.setSelectedItem("");
        comboclasstype.setSelectedItem("");
        ComboBatch.setSelectedItem("");
        setenableupdateform(false);
    }

    private void setenableupdateform(boolean bool) {
        comboDate.setEnabled(bool);
        comboclassplace.setEnabled(bool);
        comboclasstype.setEnabled(bool);
        ComboBatch.setEnabled(bool);

        SpinnerEndTimeH.setEnabled(bool);
        SpinnerEndTimeM.setEnabled(bool);
        SpinnerStartTimeH.setEnabled(bool);
        SpinnerStartTimeM.setEnabled(bool);

        butupdate.setEnabled(bool);

    }

    private void butupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butupdateActionPerformed
        update();

    }//GEN-LAST:event_butupdateActionPerformed

    private void comboSelectDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSelectDateItemStateChanged

        TblTimeTable.setModel(Table.SetTimeTable(comboSelectDate.getSelectedItem().toString().trim()));

    }//GEN-LAST:event_comboSelectDateItemStateChanged

    private void TblTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblTimeTableMouseClicked
        DeleteOrUpdate();

    }//GEN-LAST:event_TblTimeTableMouseClicked

    private void radioDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeleteActionPerformed
        setenableupdateform(false);
    }//GEN-LAST:event_radioDeleteActionPerformed

    private void radioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUpdateActionPerformed
        butDelete.setEnabled(false);
    }//GEN-LAST:event_radioUpdateActionPerformed

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        Delete();

    }//GEN-LAST:event_butDeleteActionPerformed

    private void comboclassplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboclassplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboclassplaceActionPerformed

    private void comboclassplaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboclassplaceItemStateChanged
        ComboBatch.setModel(ComboBox.SetBatchyear(comboclassplace.getSelectedItem().toString().trim()));
    }//GEN-LAST:event_comboclassplaceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEditTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEditTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEditTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEditTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUIEditTimeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBatch;
    private javax.swing.JSpinner SpinnerEndTimeH;
    private javax.swing.JSpinner SpinnerEndTimeM;
    private javax.swing.JSpinner SpinnerStartTimeH;
    private javax.swing.JSpinner SpinnerStartTimeM;
    private javax.swing.JTable TblTimeTable;
    private javax.swing.JButton butDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton butupdate;
    private javax.swing.JComboBox comboDate;
    private javax.swing.JComboBox comboSelectDate;
    private javax.swing.JComboBox comboclassplace;
    private javax.swing.JComboBox comboclasstype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane leyerBackground;
    private javax.swing.JLayeredPane leyerDisigng;
    private javax.swing.JLayeredPane leyerupdate;
    private javax.swing.JRadioButton radioDelete;
    private javax.swing.JRadioButton radioUpdate;
    // End of variables declaration//GEN-END:variables
}
