/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bean.Student;
import DAO.SelectStudentData;
import DAO.UpdateStudentData;
import Mannager.ComboBox;
import Mannager.DateTime;
import Mannager.StudentRegisterOrUpdate;
import Mannager.TextBoxValidation;
import Mannager.Uplod;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Chazool
 */
public class GUIStudentRegistation extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIStudentRegistation() {
        initComponents();
        // lording();
        NextBackButton();
        load();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    /**
     * No 1 = Register, No 2 = Update
     */
    public static int RegOrUp = 2;

    private void load() {

        comboClassPlace.setModel(ComboBox.SetClassPlace());
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ClassPlaceAddDelete = new javax.swing.ButtonGroup();
        leyerBackground = new javax.swing.JLayeredPane();
        leyerDisigng = new javax.swing.JLayeredPane();
        TabStdReg = new javax.swing.JTabbedPane();
        Tab1LeyerBackground = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        txtIndex = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboBatchYear = new javax.swing.JComboBox();
        comboClassPlace = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPhoneHome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radiofemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtimagepath = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        txtPhoneMobile = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        calDOB = new com.toedter.calendar.JDateChooser();
        lblTab1Background = new javax.swing.JLabel();
        Tab2LeyerBackground = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        ComboOlResultEnglish = new javax.swing.JComboBox();
        jLabel77 = new javax.swing.JLabel();
        ComboOlResulHistory = new javax.swing.JComboBox();
        jLabel78 = new javax.swing.JLabel();
        ComboOlResultMaths = new javax.swing.JComboBox();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        ComboOlResultReligion = new javax.swing.JComboBox();
        ComboOlResultSinhala = new javax.swing.JComboBox();
        ComboOlResultScience = new javax.swing.JComboBox();
        jLabel81 = new javax.swing.JLabel();
        combo_ol_subject1 = new javax.swing.JComboBox();
        ComboOlResultsub1 = new javax.swing.JComboBox();
        ComboOlResultsub2 = new javax.swing.JComboBox();
        ComboOlResultsub3 = new javax.swing.JComboBox();
        combo_ol_subject3 = new javax.swing.JComboBox();
        jLabel83 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        combo_ol_subject2 = new javax.swing.JComboBox();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel70 = new javax.swing.JLabel();
        txtolindex1 = new javax.swing.JTextField();
        coboOL1stYear = new javax.swing.JComboBox();
        jLabel71 = new javax.swing.JLabel();
        txtolindex2 = new javax.swing.JTextField();
        coboOL2ndYear = new javax.swing.JComboBox();
        lblTab2Background = new javax.swing.JLabel();
        Tab3LeyerBackground = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtParentFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtParentLname = new javax.swing.JTextField();
        txtParentNIC = new javax.swing.JTextField();
        txtParentPhone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comborelationship = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        lblTab3Background = new javax.swing.JLabel();
        jLayeredPane17 = new javax.swing.JLayeredPane();
        butBack = new javax.swing.JButton();
        butRegOrUp = new javax.swing.JToggleButton();
        butNext = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Managment");

        TabStdReg.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index :");

        txtIndex.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtIndex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIndexKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtIndex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class Place :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Batch :");

        ComboBatchYear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ComboBatchYear.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ComboBatchYearHierarchyChanged(evt);
            }
        });

        comboClassPlace.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboClassPlace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboClassPlaceItemStateChanged(evt);
            }
        });
        comboClassPlace.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comboClassPlaceHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(comboClassPlace, 0, 129, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(ComboBatchYear, 0, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(ComboBatchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboClassPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane5.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(ComboBatchYear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(comboClassPlace, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });

        txtMname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMnameKeyTyped(evt);
            }
        });

        txtNic.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNicKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC :");

        txtsname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsnameKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sure");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("second");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone :");

        txtPhoneHome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPhoneHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneHomeKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("D.O.B :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender :");

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radioMale.setForeground(new java.awt.Color(255, 255, 255));
        radioMale.setText("Male");
        radioMale.setContentAreaFilled(false);

        buttonGroup1.add(radiofemale);
        radiofemale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radiofemale.setForeground(new java.awt.Color(255, 255, 255));
        radiofemale.setText("Female");
        radiofemale.setContentAreaFilled(false);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtaddress.setColumns(12);
        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtaddress.setRows(4);
        txtaddress.setTabSize(4);
        jScrollPane1.setViewportView(txtaddress);

        txtimagepath.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email :");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblimage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txtPhoneMobile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPhoneMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneMobileKeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(calDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(radioMale)
                                .addGap(18, 18, 18)
                                .addComponent(radiofemale)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPhoneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(txtimagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(69, 69, 69))))))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(20, 20, 20)
                            .addComponent(txtPhoneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(calDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(radioMale)
                                .addComponent(radiofemale))))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtimagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2)))
                .addGap(48, 48, 48))
        );
        jLayeredPane3.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtFname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtMname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtNic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtsname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtPhoneHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(radioMale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(radiofemale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtimagepath, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblimage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtPhoneMobile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(calDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tab1LeyerBackground.add(jLayeredPane3);
        jLayeredPane3.setBounds(0, 0, 1100, 470);

        lblTab1Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        Tab1LeyerBackground.add(lblTab1Background);
        lblTab1Background.setBounds(0, 0, 1100, 470);

        TabStdReg.addTab(" Step 1 ", Tab1LeyerBackground);

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Science :");

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("English :");

        ComboOlResultEnglish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultEnglish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultEnglishActionPerformed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("History :");

        ComboOlResulHistory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResulHistory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResulHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResulHistoryActionPerformed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Mathematics :");

        ComboOlResultMaths.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultMaths.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultMathsActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Sinhala :");

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Religion :");

        ComboOlResultReligion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultReligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultReligionActionPerformed(evt);
            }
        });

        ComboOlResultSinhala.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultSinhala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultSinhala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultSinhalaActionPerformed(evt);
            }
        });

        ComboOlResultScience.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultScience.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultScienceActionPerformed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Subject 1 :");

        combo_ol_subject1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        combo_ol_subject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Business & Accounting Studies", "Citizenship Education & Governance", "Entrepreneurship Studies", "Second Language (Sinhala)", "Second Language (Tamil)", "Pali", "Sanskrit", "French", "German", "Hindi", "Japanese", "Arabic" }));

        ComboOlResultsub1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultsub1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultsub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultsub1ActionPerformed(evt);
            }
        });

        ComboOlResultsub2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultsub2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultsub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultsub2ActionPerformed(evt);
            }
        });

        ComboOlResultsub3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboOlResultsub3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B", "C", "S", "F", "ab" }));
        ComboOlResultsub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOlResultsub3ActionPerformed(evt);
            }
        });

        combo_ol_subject3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        combo_ol_subject3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Information & Communication Technology", "Agriculture & Food Technology", "Design & Technology", "Art & Crafts", "Home Economics", "Health & Physical Education", "Communication & Media Studies", "Electronic Writing Shorthand (Sinhala)", "Electronic Writing Shorthand (Tamil)", "Electronic Writing Shorthand (English)", " " }));

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Subject 3 :");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Subject 2 :");

        combo_ol_subject2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        combo_ol_subject2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Music (Oriental)", "Music (Western)", "Music (Carnatic)", "Art", "Dancing (Oriental)", "Dancing (Bharatha)", "Appreciation of English Literary Texts", "Appreciation of Sinhala Literary Texts", "Appreciation of Arabic Literary Texts", "Drama & Theatre (Sinhala)", "Drama & Theatre (Tamil)", "Drama & Theater (English)", " " }));
        combo_ol_subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ol_subject2ActionPerformed(evt);
            }
        });

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Index"));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("1st Sitting :");

        txtolindex1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtolindex1.setForeground(new java.awt.Color(0, 51, 153));
        txtolindex1.setPreferredSize(new java.awt.Dimension(6, 35));
        txtolindex1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtolindex1KeyTyped(evt);
            }
        });

        coboOL1stYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coboOL1stYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2010" }));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("2nd Sitting :");

        txtolindex2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtolindex2.setForeground(new java.awt.Color(0, 51, 153));
        txtolindex2.setPreferredSize(new java.awt.Dimension(6, 35));
        txtolindex2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtolindex2KeyTyped(evt);
            }
        });

        coboOL2ndYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coboOL2ndYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2010" }));

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70)
                .addGap(28, 28, 28)
                .addComponent(txtolindex1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(coboOL1stYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel71)
                .addGap(18, 18, 18)
                .addComponent(txtolindex2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coboOL2ndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtolindex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70)
                    .addComponent(coboOL1stYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71)
                    .addComponent(txtolindex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coboOL2ndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jLayeredPane6.setLayer(jLabel70, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtolindex1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(coboOL1stYear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel71, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtolindex2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(coboOL2ndYear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel75)
                                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel77)
                                        .addComponent(jLabel76))))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel81))
                                    .addComponent(jLabel82)
                                    .addComponent(jLabel83))))
                        .addGap(27, 27, 27)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combo_ol_subject2, 0, 0, Short.MAX_VALUE)
                                    .addComponent(combo_ol_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_ol_subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboOlResultsub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResultsub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResultsub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboOlResultScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResulHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResultEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel80)
                                    .addComponent(jLabel79)
                                    .addComponent(jLabel78))
                                .addGap(42, 42, 42)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboOlResultMaths, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResultSinhala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboOlResultReligion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(ComboOlResultScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(ComboOlResultEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel76)))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(ComboOlResulHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel78)
                            .addComponent(ComboOlResultMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboOlResultSinhala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboOlResultReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80))))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jLabel81)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel82)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel83))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(ComboOlResultsub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ComboOlResultsub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(ComboOlResultsub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(combo_ol_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(combo_ol_subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_ol_subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4.setLayer(jLabel75, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel76, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultEnglish, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel77, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResulHistory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel78, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultMaths, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel79, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel80, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultReligion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultSinhala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultScience, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel81, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(combo_ol_subject1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultsub1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultsub2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ComboOlResultsub3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(combo_ol_subject3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel83, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel82, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(combo_ol_subject2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLayeredPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tab2LeyerBackground.add(jLayeredPane4);
        jLayeredPane4.setBounds(0, 0, 1100, 470);

        lblTab2Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        Tab2LeyerBackground.add(lblTab2Background);
        lblTab2Background.setBounds(0, 0, 2560, 1440);

        TabStdReg.addTab(" Step 2", Tab2LeyerBackground);

        txtParentFname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtParentFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParentFnameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Parent Name :");

        txtParentLname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtParentLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParentLnameKeyTyped(evt);
            }
        });

        txtParentNIC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtParentNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParentNICKeyTyped(evt);
            }
        });

        txtParentPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtParentPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParentPhoneKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Relationship :");

        comborelationship.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comborelationship.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Father", "Mother", "Steward" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NIC :");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtParentLname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtParentFname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtParentNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtParentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel22)
                        .addGap(16, 16, 16)
                        .addComponent(comborelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtParentFname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtParentLname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtParentNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtParentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(comborelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(txtParentFname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtParentLname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtParentNIC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtParentPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comborelationship, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tab3LeyerBackground.add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1100, 470);

        lblTab3Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        Tab3LeyerBackground.add(lblTab3Background);
        lblTab3Background.setBounds(0, 0, 2560, 1440);

        TabStdReg.addTab(" Step 3", Tab3LeyerBackground);

        jLayeredPane17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        butBack.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        butBack.setText(" Previous ");
        butBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        butRegOrUp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        butRegOrUp.setText("Registor");
        butRegOrUp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        butRegOrUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegOrUpActionPerformed(evt);
            }
        });

        butNext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        butNext.setText(" Next ");
        butNext.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        butNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane17Layout = new javax.swing.GroupLayout(jLayeredPane17);
        jLayeredPane17.setLayout(jLayeredPane17Layout);
        jLayeredPane17Layout.setHorizontalGroup(
            jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane17Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(butBack)
                .addGap(359, 359, 359)
                .addComponent(butRegOrUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butNext)
                .addContainerGap())
        );
        jLayeredPane17Layout.setVerticalGroup(
            jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane17Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jLayeredPane17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBack)
                    .addComponent(butRegOrUp)
                    .addComponent(butNext))
                .addGap(31, 31, 31))
        );
        jLayeredPane17.setLayer(butBack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane17.setLayer(butRegOrUp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane17.setLayer(butNext, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout leyerDisigngLayout = new javax.swing.GroupLayout(leyerDisigng);
        leyerDisigng.setLayout(leyerDisigngLayout);
        leyerDisigngLayout.setHorizontalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabStdReg, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(jLayeredPane17)
        );
        leyerDisigngLayout.setVerticalGroup(
            leyerDisigngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leyerDisigngLayout.createSequentialGroup()
                .addComponent(TabStdReg, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        leyerDisigng.setLayer(TabStdReg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        leyerDisigng.setLayer(jLayeredPane17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leyerBackground.add(leyerDisigng);
        leyerDisigng.setBounds(0, 0, 1100, 640);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/BG Image.jpg"))); // NOI18N
        leyerBackground.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 630);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leyerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1120, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtParentPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParentPhoneKeyTyped
        TextBoxValidation.KeyType(evt, txtParentPhone.getText());
    }//GEN-LAST:event_txtParentPhoneKeyTyped

    private void txtParentNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParentNICKeyTyped
        TextBoxValidation.KeyType(evt, txtParentNIC.getText().length());
    }//GEN-LAST:event_txtParentNICKeyTyped

    private void txtParentLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParentLnameKeyTyped
        TextBoxValidation.KeyType(evt);
    }//GEN-LAST:event_txtParentLnameKeyTyped

    private void txtParentFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParentFnameKeyTyped
        TextBoxValidation.KeyType(evt);
    }//GEN-LAST:event_txtParentFnameKeyTyped

    private void txtolindex2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtolindex2KeyTyped
        TextBoxValidation.KeyType(evt, WIDTH);
    }//GEN-LAST:event_txtolindex2KeyTyped

    private void txtolindex1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtolindex1KeyTyped
        TextBoxValidation.KeyType(evt, WIDTH);
    }//GEN-LAST:event_txtolindex1KeyTyped

    private void combo_ol_subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ol_subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ol_subject2ActionPerformed

    private void ComboOlResultsub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultsub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultsub3ActionPerformed

    private void ComboOlResultsub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultsub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultsub2ActionPerformed

    private void ComboOlResultsub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultsub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultsub1ActionPerformed

    private void ComboOlResultScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultScienceActionPerformed

    private void ComboOlResultSinhalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultSinhalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultSinhalaActionPerformed

    private void ComboOlResultReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultReligionActionPerformed

    private void ComboOlResultMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultMathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultMathsActionPerformed

    private void ComboOlResulHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResulHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResulHistoryActionPerformed

    private void ComboOlResultEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOlResultEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboOlResultEnglishActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        lblimage.setIcon(Uplod.ImageIcon(lblimage.getWidth(), lblimage.getHeight()));
        txtimagepath.setText(Uplod.Imagepath);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPhoneMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneMobileKeyTyped
        TextBoxValidation.KeyType(evt, txtPhoneMobile.getText());
    }//GEN-LAST:event_txtPhoneMobileKeyTyped

    private void txtPhoneHomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneHomeKeyTyped
        TextBoxValidation.KeyType(evt, txtPhoneHome.getText());
    }//GEN-LAST:event_txtPhoneHomeKeyTyped

    private void txtsnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsnameKeyTyped
        TextBoxValidation.KeyType(evt);
    }//GEN-LAST:event_txtsnameKeyTyped

    private void txtNicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyTyped
        TextBoxValidation.KeyType(evt, txtNic.getText().length());
    }//GEN-LAST:event_txtNicKeyTyped

    private void txtMnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMnameKeyTyped
        TextBoxValidation.KeyType(evt);
    }//GEN-LAST:event_txtMnameKeyTyped

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped
        TextBoxValidation.KeyType(evt);
    }//GEN-LAST:event_txtFnameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Select();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIndexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndexKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Select();
        }
    }//GEN-LAST:event_txtIndexKeyPressed

    private void butRegOrUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegOrUpActionPerformed

        if (!UpdateStudentData.setdata(ReturnStudent())) {
            System.out.println("Susssssss");
        } else {
            System.out.println("Unsuccc");
        }
//        StudentRegisterOrUpdate.SetData(ReturnStudent());
    }//GEN-LAST:event_butRegOrUpActionPerformed

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        TabStdReg.setSelectedIndex(TabStdReg.getSelectedIndex() - 1);
        NextBackButton();
    }//GEN-LAST:event_butBackActionPerformed

    private void butNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNextActionPerformed
        TabStdReg.setSelectedIndex(TabStdReg.getSelectedIndex() + 1);
        NextBackButton();
    }//GEN-LAST:event_butNextActionPerformed

    private void comboClassPlaceHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comboClassPlaceHierarchyChanged

    }//GEN-LAST:event_comboClassPlaceHierarchyChanged

    private void ComboBatchYearHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ComboBatchYearHierarchyChanged


    }//GEN-LAST:event_ComboBatchYearHierarchyChanged

    private void comboClassPlaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboClassPlaceItemStateChanged
        ComboBatchYear.setModel(ComboBox.SetBatchyear(comboClassPlace.getSelectedItem().toString()));
    }//GEN-LAST:event_comboClassPlaceItemStateChanged

    private void Select() {
        // Update Data
        // Set Student Data

        Student std = SelectStudentData.selectdata(txtIndex.getText().trim());

        comboClassPlace.setSelectedItem(std.getBadgeYear());
        ComboBatchYear.setSelectedItem(std.getClassplasse());
        txtFname.setText(std.getFname());
        txtMname.setText(std.getMname());
        txtsname.setText(std.getSname());
        txtNic.setText(std.getNic());
        calDOB.setToolTipText(std.getDob());
        String gender = std.getGender();

        if (null != gender) {
            switch (gender) {
                case "m":
                    radioMale.setSelected(true);
                    break;
                case "f":
                    radiofemale.setSelected(true);
                    break;
            }
        }

        txtaddress.setText(std.getAddress());
        txtPhoneHome.setText(std.getPhonehome());
        txtPhoneMobile.setText(std.getPhonemobile());
        txtEmail.setText(std.getEmail());
        txtimagepath.setText("");
            //  End Set Student Data

        // Set OL Result 
        txtolindex1.setText(std.getOLIndex1());
        coboOL1stYear.setSelectedItem(std.getOL1stYear());
        txtolindex2.setText(std.getOLIndex2());
        coboOL2ndYear.setSelectedItem(std.getOL2ndYear());

        ComboOlResultScience.setSelectedItem(std.getScience());
        ComboOlResultEnglish.setSelectedItem(std.getEnglish());
        ComboOlResulHistory.setSelectedItem(std.getHistory());
        ComboOlResultMaths.setSelectedItem(std.getMaths());
        ComboOlResultSinhala.setSelectedItem(std.getSinhala());
        ComboOlResultReligion.setSelectedItem(std.getReligion());

        combo_ol_subject1.setSelectedItem(std.getSubject1());
        ComboOlResultsub1.setSelectedItem(std.getSubject1result());
        combo_ol_subject2.setSelectedItem(std.getSubject2());
        ComboOlResultsub2.setSelectedItem(std.getSubject2result());
        combo_ol_subject3.setSelectedItem(std.getSubject3());
        ComboOlResultsub3.setSelectedItem(std.getSubject3result());

        // Set Parent Data
        txtParentFname.setText(std.getPfname());
        txtParentLname.setText(std.getPlname());
        txtParentNIC.setText(std.getPnic());
        txtParentPhone.setText(std.getPphone());
        comborelationship.setSelectedItem(std.getPrelationship());

    }

    private String gender() {

        String gender = "";
        if (radioMale.isSelected()) {
            gender = "m";
        } else if (radiofemale.isSelected()) {
            gender = "f";
        }
        return gender;
    }

    private Student ReturnStudent() {
        // Update Data
        Student slc = new Student();
        // Student Data
        slc.setIndex(txtIndex.getText().trim());
        slc.setBadgeYear(comboClassPlace.getSelectedItem().toString());
        slc.setClassplasse(ComboBatchYear.getSelectedItem().toString());
        slc.setFname(txtFname.getText());
        slc.setMname(txtMname.getText());
        slc.setSname(txtsname.getText());
        slc.setNic(txtNic.getText());
        slc.setDob(DateTime.GetStringDate(calDOB.getDate()));
        slc.setGender(gender());
        slc.setAddress(txtaddress.getText());
        slc.setPhonehome(txtPhoneHome.getText());
        slc.setPhonemobile(txtPhoneMobile.getText());
        slc.setEmail(txtEmail.getText());
        slc.setImagepath(txtimagepath.getText());

        // OL Data
        slc.setOLIndex1(txtolindex1.getText());
        slc.setOLIndex2(txtolindex2.getText());
        slc.setScience(ComboOlResultScience.getSelectedItem().toString());
        slc.setEnglish(ComboOlResultEnglish.getSelectedItem().toString());
        slc.setHistory(ComboOlResulHistory.getSelectedItem().toString());
        slc.setMaths(ComboOlResultMaths.getSelectedItem().toString());
        slc.setSinhala(ComboOlResultSinhala.getSelectedItem().toString());
        slc.setReligion(ComboOlResultReligion.getSelectedItem().toString());
        slc.setSubject1(combo_ol_subject1.getSelectedItem().toString());
        slc.setSubject1result(ComboOlResultsub1.getSelectedItem().toString());
        slc.setSubject2(combo_ol_subject2.getSelectedItem().toString());
        slc.setSubject2result(ComboOlResultsub2.getSelectedItem().toString());
        slc.setSubject3(combo_ol_subject3.getSelectedItem().toString());
        slc.setSubject3result(ComboOlResultsub3.getSelectedItem().toString());
        slc.setOL1stYear(coboOL1stYear.getSelectedItem().toString());
        slc.setOL2ndYear(coboOL2ndYear.getSelectedItem().toString());

        // Prent Data
        slc.setPfname(txtParentFname.getText());
        slc.setPlname(txtParentLname.getText());
        slc.setPphone(txtParentPhone.getText());
        slc.setPrelationship(comborelationship.getSelectedItem().toString());
        slc.setPnic(txtParentNIC.getText());
        return slc;
    }

    private boolean check() {

        boolean b = true;

        String fname = txtFname.getText();
        String mname = txtMname.getText();
        String sname = txtsname.getText();
        String nic = txtNic.getText();
        // dob = caldob.getDateFormatString();//null
        String address = txtaddress.getText();
        String phonehome = txtPhoneHome.getText();
        String phonemobile = txtPhoneMobile.getText();
        String email = txtEmail.getText();
        //  gendergroop=   gendergroop.;
        String imagepath = txtimagepath.getText();

        // Set OL Result 
        String olindex1 = txtolindex1.getText();//null
        String olyear1 = coboOL1stYear.getSelectedItem().toString();//null
        String olindex2 = txtolindex2.getText();//null
        String olyear2 = coboOL2ndYear.getSelectedItem().toString();//null

        String olscience = ComboOlResultScience.getSelectedItem().toString();//null
        String olenglish = ComboOlResultEnglish.getSelectedItem().toString();//null
        String olhistory = ComboOlResulHistory.getSelectedItem().toString();//null
        String olmaths = ComboOlResultMaths.getSelectedItem().toString();//null
        String olsinhala = ComboOlResultSinhala.getSelectedItem().toString();//null
        String olreligion = ComboOlResultReligion.getSelectedItem().toString();//null

        String olsubject1 = combo_ol_subject1.getSelectedItem().toString();//null
        String olsubject1result = ComboOlResultsub1.getSelectedItem().toString();//null
        String olsubject2 = combo_ol_subject2.getSelectedItem().toString();//null
        String olsubject2result = ComboOlResultsub2.getSelectedItem().toString();//null
        String olsubject3 = combo_ol_subject3.getSelectedItem().toString();//null
        String olsubject3result = ComboOlResultsub3.getSelectedItem().toString();//null

        // Set Parent Data
        String perentfname = txtParentFname.getText();//null
        String perentlname = txtParentLname.getText();//null
        String perentnic = txtParentNIC.getText();//null
        String perentphone = txtParentPhone.getText();//null
        String perentrelationship = comborelationship.getSelectedItem().toString();//null

        String Massage = "";

        if ("".equals(fname) || fname.length() < 2) {
            txtFname.setBackground(Color.red);
            Massage = Massage + "First Name,";
            b = false;
        } else {

            txtMname.setBackground(getBackground());
        }
        if (sname.equals("") || sname.length() < 2) {
            txtsname.setBackground(Color.red);
            Massage = Massage + "Sure Name,";
            b = false;
        } else {

            txtsname.setBackground(getBackground());
        }

        if (nic.equals("") || nic.length() < 9) {
            txtNic.setBackground(Color.red);
            Massage = Massage + "NIC,";
            b = false;
        } else {
            txtNic.setBackground(getBackground());
        }
        if (!(radioMale.isSelected() || radiofemale.isSelected())) {
            radioMale.setForeground(Color.red);
            radiofemale.setForeground(Color.red);

            Massage = Massage + "Gender,";
        } else {
            radioMale.setForeground(getBackground());
            radiofemale.setForeground(getBackground());
        }

        if (address.equals("") || address.length() < 5) {
            txtaddress.setBackground(Color.red);
            Massage = Massage + "Address,";
            b = false;
        } else {
            txtaddress.setBackground(getBackground());
        }
        if (phonehome.equals("") || phonehome.length() < 9) {
            txtPhoneHome.setBackground(Color.red);
            Massage = Massage + "Phone Home, ";
            b = false;
        } else {
            txtPhoneMobile.setBackground(getBackground());
        }
        if (!phonemobile.equals("") && phonemobile.length() < 9) {
            txtPhoneMobile.setBackground(Color.red);
            Massage = Massage + "Phone Mobile,";
            b = false;
        } else {
            txtPhoneMobile.setBackground(getBackground());
        }

        if (imagepath.equals("")) {

        }

        if (olindex1.equals("")) {
            txtolindex1.setBackground(Color.red);
            Massage = Massage + "O/L Index,";
            b = false;
        } else {
            txtolindex1.setBackground(getBackground());
        }
        if (olyear1.equals(" ")) {
            coboOL1stYear.setBackground(Color.red);
            Massage = Massage + "O/L Year,";
            b = false;
        } else {
            coboOL1stYear.setBackground(getBackground());
        }

        if (olscience.equals(" ")) {
            ComboOlResultScience.setBackground(Color.red);
            Massage = Massage + "Science Result,";
            b = false;
        } else {
            ComboOlResultScience.setBackground(getBackground());
        }

        if (olenglish.equals(" ")) {
            ComboOlResultEnglish.setBackground(Color.red);
            Massage = Massage + "English Result,";
            b = false;
        } else {
            ComboOlResultEnglish.setBackground(getBackground());
        }

        if (olhistory.equals(" ")) {
            ComboOlResulHistory.setBackground(Color.red);
            Massage = Massage + "History Result,";
            b = false;
        } else {
            ComboOlResulHistory.setBackground(getBackground());
        }

        if (olmaths.equals(" ")) {
            ComboOlResultMaths.setBackground(Color.red);
            Massage = Massage + "Mathematics Result,";
            b = false;
        } else {
            ComboOlResultMaths.setBackground(getBackground());
        }

        if (olsinhala.equals(" ")) {
            ComboOlResultSinhala.setBackground(Color.red);
            Massage = Massage + "Sinhala Result,";
            b = false;
        } else {
            ComboOlResultSinhala.setBackground(getBackground());
        }

        if (olreligion.equals(" ")) {
            ComboOlResultReligion.setBackground(Color.red);
            Massage = Massage + "Religion Result,";
            b = false;
        } else {
            ComboOlResultReligion.setBackground(getBackground());
        }

        if (olsubject1.equals(" ")) {
            combo_ol_subject1.setBackground(Color.red);
            Massage = Massage + "Subject 1,";
            b = false;
        } else {
            combo_ol_subject1.setBackground(getBackground());
        }

        if (olsubject1result.equals(" ")) {
            ComboOlResultsub1.setBackground(Color.red);
            Massage = Massage + "Subject 1 Result,";
            b = false;
        } else {
            ComboOlResultsub1.setBackground(getBackground());
        }

        if (olsubject2.equals(" ")) {
            combo_ol_subject2.setBackground(Color.red);
            Massage = Massage + "Subject 2,";
            b = false;
        } else {
            combo_ol_subject2.setBackground(getBackground());
        }

        if (olsubject2result.equals(" ")) {
            ComboOlResultsub2.setBackground(Color.red);
            Massage = Massage + "Subject 2 Result,";
            b = false;
        } else {
            ComboOlResultsub2.setBackground(getBackground());
        }

        if (olsubject3.equals(" ")) {
            combo_ol_subject3.setBackground(Color.red);
            Massage = Massage + "Subject 3,";
            b = false;
        } else {
            combo_ol_subject3.setBackground(getBackground());
        }

        if (olsubject3result.equals(" ")) {
            ComboOlResultsub3.setBackground(Color.red);
            Massage = Massage + "Subject 3 Result,";
            b = false;
        } else {
            ComboOlResultsub3.setBackground(getBackground());
        }

        if (perentfname.equals("")) {
            txtParentFname.setBackground(Color.red);
            Massage = Massage + "Perent First Name,";
            b = false;
        } else {
            txtParentFname.setBackground(getBackground());
        }
        if (perentlname.equals("")) {
            txtParentLname.setBackground(Color.red);
            Massage = Massage + "Perent Last Name,";
            b = false;
        } else {
            txtParentLname.setBackground(getBackground());
        }

        if (perentnic.equals("")) {
            txtParentNIC.setBackground(Color.red);
            Massage = Massage + "Perent NIC,";
            b = false;
        } else {
            txtParentNIC.setBackground(getBackground());
        }
        if (perentphone.equals("")) {
            txtParentPhone.setBackground(Color.red);
            Massage = Massage + "Perent Phone,";
            b = false;
        } else {
            txtParentPhone.setBackground(getBackground());
        }

        if (perentrelationship.equals(" ")) {
            comborelationship.setBackground(Color.red);
            Massage = Massage + "Perent Phone,";
            b = false;
        } else {
            comborelationship.setBackground(getBackground());
        }

        return b;
    }

    private void lording() {
        comboClassPlace.setModel(ComboBox.SetBatchyear(ComboBatchYear.getSelectedItem().toString()));
        ComboBatchYear.setModel(ComboBox.SetClassPlace());

    }

    private void NextBackButton() {
        int Tabindex = TabStdReg.getSelectedIndex();

        switch (Tabindex) {
            case 0: {
                butBack.setVisible(false);
                butNext.setVisible(true);
                break;
            }
            case 1: {
                butBack.setVisible(true);
                butNext.setVisible(true);
                break;
            }
            case 2: {
                butBack.setVisible(true);
                butNext.setVisible(false);
                break;
            }

        }

    }

    public void A(int No) {

        switch (No) {
            case 1: {
                txtIndex.setEditable(false);
                butRegOrUp.setText("Register");
                break;
            }
            case 2: {
                txtIndex.setEditable(true);
                butRegOrUp.setText("Update");
                break;
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStudentRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStudentRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStudentRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStudentRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStudentRegistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ClassPlaceAddDelete;
    private javax.swing.JComboBox ComboBatchYear;
    private javax.swing.JComboBox ComboOlResulHistory;
    private javax.swing.JComboBox ComboOlResultEnglish;
    private javax.swing.JComboBox ComboOlResultMaths;
    private javax.swing.JComboBox ComboOlResultReligion;
    private javax.swing.JComboBox ComboOlResultScience;
    private javax.swing.JComboBox ComboOlResultSinhala;
    private javax.swing.JComboBox ComboOlResultsub1;
    private javax.swing.JComboBox ComboOlResultsub2;
    private javax.swing.JComboBox ComboOlResultsub3;
    private javax.swing.JLayeredPane Tab1LeyerBackground;
    private javax.swing.JLayeredPane Tab2LeyerBackground;
    private javax.swing.JLayeredPane Tab3LeyerBackground;
    private javax.swing.JTabbedPane TabStdReg;
    private javax.swing.JButton butBack;
    private javax.swing.JToggleButton butNext;
    private javax.swing.JToggleButton butRegOrUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calDOB;
    private javax.swing.JComboBox coboOL1stYear;
    private javax.swing.JComboBox coboOL2ndYear;
    private javax.swing.JComboBox comboClassPlace;
    private javax.swing.JComboBox combo_ol_subject1;
    private javax.swing.JComboBox combo_ol_subject2;
    private javax.swing.JComboBox combo_ol_subject3;
    private javax.swing.JComboBox comborelationship;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane17;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTab1Background;
    private javax.swing.JLabel lblTab2Background;
    private javax.swing.JLabel lblTab3Background;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLayeredPane leyerBackground;
    private javax.swing.JLayeredPane leyerDisigng;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radiofemale;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtIndex;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtParentFname;
    private javax.swing.JTextField txtParentLname;
    private javax.swing.JTextField txtParentNIC;
    private javax.swing.JTextField txtParentPhone;
    private javax.swing.JTextField txtPhoneHome;
    private javax.swing.JTextField txtPhoneMobile;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtimagepath;
    private javax.swing.JTextField txtolindex1;
    private javax.swing.JTextField txtolindex2;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
}
